-- Cria a tabela que representa as tarefas persistidas pela aplicação.
CREATE TABLE tarefas (
    -- Cria uma chave numérica gerada automaticamente pelo PostgreSQL.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Guarda o título obrigatório da tarefa.
    titulo VARCHAR(255) NOT NULL,
    -- Guarda o estado da tarefa e inicia novos registros como pendentes.
    concluida BOOLEAN NOT NULL DEFAULT FALSE,
    -- Guarda o nome obrigatório do responsável.
    responsavel VARCHAR(255) NOT NULL,
    -- Guarda a data limite obrigatória da tarefa.
    data_prazo DATE NOT NULL,
    -- Guarda a data de criação e usa a data atual como padrão.
    data_cadastro DATE NOT NULL DEFAULT CURRENT_DATE
);

-- Insere os dois registros de exemplo usados pela aula.
INSERT INTO tarefas (titulo, responsavel, data_prazo)
-- Usa a data atual para calcular os prazos dos exemplos.
VALUES
    -- Cria uma tarefa com prazo para sete dias depois da migration.
    ('Preparar slides da Aula 08', 'Daniel', CURRENT_DATE + 7),
    -- Cria uma tarefa com prazo para três dias depois da migration.
    ('Corrigir exercícios da Aula 07', 'Daniel', CURRENT_DATE + 3);
